id: P003205
initial_creation_type: ocr
source_metadata:
  id: bdr:W18120
  title: བདུད་རྩི་སྨན་གྱི་རྣམ་བཤད་བློ་གསར་དགའ་སྟོན
  author: ''
  volumes:
    c0037794ad8c4d93a9a7dda1f6f5cf6a:
      image_group_id: I4841
      title: ''
      volume_number: 1
      total_pages: 351
      base_file: v001.txt
